---
title: "Simulation"
author: "Saryu Patel"
date: "11/10/2021"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

## Simulate something

```{r}
sim_mean_sd = function(samp_size, mu = 3, sigma = 4) {
  sim_data <- tibble(
    x = rnorm(n = samp_size, mean = mu, sd = sigma),
  )
  sim_data %>% 
    summarize(
      mean = mean(x),
      sd = sd(x)
    )
}
```

Simulate by running this line. 

```{r}
sim_mean_sd(30)
```

## Simulate a lot

Start with a for loop.

```{r}
output <- vector("list", length = 100)

for (i in 1:100) {
  output[[i]] <- sim_mean_sd(samp_size = 30)
}

bind_rows(output)
```

Use a loop function.

```{r}
sim_results <- 
  rerun(100, sim_mean_sd(30)) %>%
    bind_rows()
```

Look at results.

```{r}
sim_results %>% 
  ggplot(aes(x = mean)) +
  geom_density()

sim_results %>% 
  summarize(
    avg_samp_mean = mean(mean),
    sd_sample_mean = sd(mean)
  )

sim_results %>% 
  ggplot(aes(x = sd)) +
  geom_density()
```

